FROM certbot/certbot:v0.14.2
LABEL maintainer "Ash Wilson"

RUN apk add --no-cache python3
ADD requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
ADD script/certbot /app/script/certbot/
ADD script/ci/common.sh /app/script/ci/common.sh
ADD script/ci/cron /app/script/ci/cron
WORKDIR /app

ENTRYPOINT ["/app/script/ci/cron"]
